server:
  port: 8925
  servlet:
    context-path: /xijiang
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.50.82.93:3306/xijiang?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: dtwave@123

